### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by rezar12** [sintefmath/implicit-recon#4]
need help!! i need the dataset for the Example after contacting Dr. Xiaowei Xu i received no answer ... if not how to use own dataset as example ...

**Comment by georgmuntingh** [comment]
Dear rezar12,

Dr. Xiawei Xu graciously shared his dataset with us, but unfortunately I cannot share the dataset with you without his permission.

Kind regards,
Georg.

**Comment by rezar12** [comment]
THANK ...
