### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by fatola03** [sintefmath/implicit-recon#5]
Dear Georg,
Dr. Xiawei Xu shared dataset ... but i have a new problem dataset shared image is down :

![Capture](https://user-images.githubusercontent.com/116105749/196500689-c925531c-375f-4a49-8e22-1913f506c4f0.PNG)
when i  run next command : 
python .\src\utilities\compute_distance_fields.py --input_dir $BASE_DATA_DIR
i have  error : 
![Capture d’écran 2022-10-18 192723](https://user-images.githubusercontent.com/116105749/196502319-e5e8de46-9b85-49e7-861a-dbfd63383c31.png)

**Comment by georgmuntingh** [comment]
Dear fatalo03,

It seems to me that the file the code is trying to access is not present in your directory.

Georg.
